### ISSUE TITLE
Debug build provides many warnings; please fix

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#162]
Debug builds are a bit ugly now in that we have many warnings. Common issues are unused variables, bad comparisons between int and size_t, and initialization ordering.

It would be nice to monitor this more closely in the future. Having a nightly debug build would be useful.

Also, we should review why we have this disparity between debug and opt. I think that it was an optimization to have opt mostly working everywhere even when small warnings were present.

I once had warnings as errors for debug active which may make things better in the future. Not sure why this was turned off.

**Comment by sayerhs** [comment]
@jrood-nrel I worked around that issue by using `-Wno-deprecated-declarations` but retaining other warnings. This is not ideal... but since we are not marking deprecations for compiler in Nalu I felt it was an acceptable choice. This still shows me warnings related to the rest of the code though.

**Comment by jrood-nrel** [comment]
@sayerhs #100

**Comment by sayerhs** [comment]
@jrood-nrel Ah, sorry, I'd missed that pull request. Forking yaml-cpp to `NaluCFD` and using a custom spack definition pointing to `develop` might be the best path forward.

**Comment by jrood-nrel** [comment]
@sayerhs That's a good idea. We could just keep our own snapshot of Yaml here.

**Comment by spdomin** [comment]
Not sure I would want to maintain a TPL. Has anyone reached out to the YAML team? We could provide a pull request to YAML?

Also, a primary intent of this issue was to actually fix the warnings that are due to Nalu developers. However, perhaps this is already done?

**Comment by sayerhs** [comment]
Looking at the yaml issue that Jon posted in #100, it appears that the
depreciation issue has been already fixed in yaml develop branch. We can
build against yaml develop and get rid of the warnings. Forking to nalu CFD
would be a temporary measure so as to not track a constantly changing yaml
devel branch, but instead use a snapshot until they release a new tagged
version.

**Comment by spdomin** [comment]
Cool. Our build process can also point to a particular SHA-1? We should probably ask that they push out a new branch/release.

**Comment by spdomin** [comment]
Working through some build issues..

@alanw0, could you look at: 

Nalu/src/Realm.C:2525:42: warning: array subscript is above array bounds [-Warray-bounds]
          minCoord[j] = std::min(minCoord[j], mCoord[k*nDim+j]);

- this is confusing me as I see nothing off.

@sayerhs, could you please push your sims branch fix for the following:

Nalu/src/user_functions/SteadyThermal3dContactSrcElemKernel.C:91:25: warning: 'w_scvCoords[2]' is used uninitialized in this function [-Wuninitialized]
        + cos(2.0*a_*pi_*z))*v_scv_volume(ip);

**Comment by alanw0** [comment]
I agree that code looks correct.
Perhaps it is because the compiler can't know that nDim is <= 3, but I don't know why it would issue a warning.

Alan


On Aug 14, 2017, at 9:10 PM, Stefan P. Domino <notifications@github.com<mailto:notifications@github.com>> wrote:


Working through some build issues..

@alanw0<https://github.com/alanw0>, could you look at:

Nalu/src/Realm.C:2525:42: warning: array subscript is above array bounds [-Warray-bounds]
minCoord[j] = std::min(minCoord[j], mCoord[k*nDim+j]);

  *   this is confusing me as I see nothing off.

@sayerhs<https://github.com/sayerhs>, could you please push your sims branch fix for the following:

Nalu/src/user_functions/SteadyThermal3dContactSrcElemKernel.C:91:25: warning: 'w_scvCoords[2]' is used uninitialized in this function [-Wuninitialized]
+ cos(2.0*a_*pi_*z))*v_scv_volume(ip);

-

**Comment by sayerhs** [comment]
@spdomin The line printed out is not consistent with the latest version of the [file](https://github.com/NaluCFD/Nalu/blob/stk_simd_kernels/src/user_functions/SteadyThermal3dContactSrcElemKernel.C#L86). I am not seeing a warning generated either with GCC 5.2.0 or OSX Clang. Can you show me your compilation command line? 

I am using this:

```
/home/sanantha/spack/opt/spack/linux-centos6-x86_64/gcc-5.2.0/openmpi-1.10.3-gp6gqlvjm25kf5n46ib5jkv3mfse377a/bin/mpicxx   -I/home/sanantha/spack/opt/spack/linux-centos6-x86_64/gcc-5.2.0/yaml-cpp-0.5.3-jfzt747wz5mlc37lx6pdsiqi6tlor5uf/include/yaml-cpp/.. -I/home/sanantha/code/nalu/spack_install/trilinos/include -I/home/sanantha/spack/opt/spack/linux-centos6-x86_64/gcc-5.2.0/superlu-4.3-hwpddgr6jnqx7t5sdufnvxv322c35zex/include -I/home/sanantha/spack/opt/spack/linux-centos6-x86_64/gcc-5.2.0/zlib-1.2.11-dayoxcvooeyba7urrdphgeqd7gr6h7xr/include -I/home/sanantha/spack/opt/spack/linux-centos6-x86_64/gcc-5.2.0/boost-1.60.0-gvcf4hewfqag4rxgk5hxs7tsmw5ygti4/include -I/home/sanantha/spack/opt/spack/linux-centos6-x86_64/gcc-5.2.0/netcdf-4.3.3.1-h3gtofi6tmyr5roiqk2qlxb7xnr6txnr/include -I/home/sanantha/spack/opt/spack/linux-centos6-x86_64/gcc-5.2.0/hdf5-1.8.16-ee2nsbowdrvy4npv6kvjlnjz4rcphoxp/include -I/home/sanantha/spack/opt/spack/linux-centos6-x86_64/gcc-5.2.0/parallel-netcdf-1.6.1-qf3bblih6x3hsfhqlgf23zrc37iqrqla/include -I/home/sanantha/code/nalu/Nalu/include  -g -Wall -pedantic  -std=c++11 -fopenmp   -O2 -g -DNDEBUG   -o CMakeFiles/nalu.dir/src/user_functions/SteadyThermal3dContactSrcElemKernel.C.o -c /home/sanantha/code/nalu/Nalu/src/user_functions/SteadyThermal3dContactSrcElemKernel.C
```

**Comment by spdomin** [comment]
I think that this might be a gcc bug on compilers lower than 4.9-ish.

**Comment by michaelasprague** [comment]
@spdomin -- has this issue been addressed to your satisfaction?  If so, can we close it?
