### ISSUE TITLE
Compiling with Intel requires "-restrict" option?

### ISSUE THREAD

**Issue by jhux2** [NaluCFD/Nalu#203]
I am compiling Nalu without spack with Intel 17.0.0 and MVAPICH.   I've found that I need to add the `-restrict` compiler option in order to compile this code in `src/master/MasterElement.h`.  

```
#ifdef __INTEL_COMPILER
#define POINTER_RESTRICT restrict
#else
#define POINTER_RESTRICT __restrict__
#endif
```

[snip]

```
  double jacobian_determinant(
    const double *POINTER_RESTRICT elemNodalCoords,
    const double *POINTER_RESTRICT shapeDerivs ) const;
```

If I omit `-restrict`, the compilation fails with this error:
```
In file included from /ascldap/users/jhu/nalu/Nalu/src/ComputeMdotAlgorithmDriver.C(15):
/ascldap/users/jhu/nalu/Nalu/include/master_element/MasterElement.h(922): error: expected a ")"
      const double *POINTER_RESTRICT elemNodalCoords,
```

I tried compiling with Intel 16, and `-restrict` is still necessary.

Reference: https://software.intel.com/en-us/forums/intel-c-compiler/topic/277016

**Comment by jrood-nrel** [comment]
@jhux2 I think this is a side effect of the changes I made to the cmakelists. It was finding the base gcc as a compiler even when using Intel. We have logic in the cmakelists for adding `-restrict` for Intel but it wasn't adding it since it was finding gcc from what I saw. I have reverted my changes. Can you try with the latest Nalu code?

**Comment by jhux2** [comment]
@jrood-nrel I updated from Nalu master, and your reverts fixed the problem.  Thanks!
