### ISSUE TITLE
Preconditioner timer reporting in EquationSystem with linear system reinitialization

### ISSUE THREAD

**Issue by sayerhs** [NaluCFD/Nalu#238]
The `timerPrecond_` is accumulated in the LinearSolver object and then output within the EquationSystem reporting method (after adjusting timerSolve_). However, when using Nalu with mesh motion, the `linearSolver_` object is destroyed and recreated within the `EquationSystem::reinitialize_linear_system` before each timestep, so it appears that the `timerPrecond_` reported in the log file only captures the time spent setting up preconditioner for the last timestep, whereas the `timerSolve_` contains the time spent setting up preconditioner at other timesteps. Is this intentional, or did I overlook the code that adjusts the `timerPrecond_` before reinitializing the linear system? If latter, can someone please point to the relevant section of the code?

Cc: @spdomin

**Comment by spdomin** [comment]
This is probably a bug in the timers that did not take in consideration the mesh modification step.

**Comment by spdomin** [comment]
I looked at the code. Definitely a problem and in need of repair. This also explains data coming from @mbarone81 and @jhux2 where we could not explain why setup was so expensive in his non-rotating simulations with and without recompute_precond().

In the end, we want solve time to still subtract out the preconditioned time, as is done in dumpEq.

I think that we could fix this many ways. One might be to have LinearSolver::timerPrecond_ wrapping the setMuelu() and other preconditioning times, i.e., without the +=. This would make the time local to each solve. We could extract this value in EquationSystem::assemble_and_solve(). We could also adjust the timerSolve_ at that point and remove this step from the EquationSystem::dump_eq_time() where the preconditioned time is removed from solve time.

Another fix would be to increment the LinearSolver::timerPrecond_ as done now and extract that before and after the destruction of the system.

I think the first solution would be more clear and avoid moving the timer calipers at matrix destruction..

Let me know how you would like to proceed. If you can move forward with the fix, that would be great. Otherwise, I can take it.

In the end, this was a great find!

**Comment by sayerhs** [comment]
@spdomin I think your first suggestion is my preference for the fix:  Change `LinearSolver::timerPrecond_` to be just the time spent setting up preconditioner at that particular solve step. The actual summing `+=` step happens within `EquationSystem::assemble_and_solve()`, and change the adjustment of `timerSolve_` in `dump_eq_time()` with `timerSolve_ -= timerPrecond_`. 

I will make the necessary modifications and submit a pull request.

**Comment by jhux2** [comment]
@sayerhs Thanks for finding this!  I was looking at the timers today, and couldn't make sense of what was reported at the end of the simulation, vs. what MueLu is self-reporting.
