### ISSUE TITLE
Mac consolidated dgThreeBlade diverging while non-consolidated runs fine.

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#302]
I have realized that a Mac simulation using the consolidated and non-consolidated Kokkos scheme behaves very differently for a slightly modified dgThreeBlade case. The consolidated approach diverges while non-consolidated runs fine. I am not sure if all of this is related to the recent Trilinos changes or an inherent difference in the implementation (possibly master elements even...). I need to look into how the Mac unit tests are doing for the momentum and continuity kernels. Side by sides of the two implementations look fine.

I plan on running this case on Linux to see if there is something odd about Mac. Thus far, the Intel production runs seem fine.

Adding the @NaluCFD/ngp team for a heads up that interior element-based kernels are looking odd on Mac. After I have the linux test done, we can see who would like to lead this investigation.

**Comment by sayerhs** [comment]
@spdomin Are you running the tests via the `ctest` interface? If not, are you explicitly setting  `OMP_NUM_THREADS=1` before running the test cases? On Mac systems,  it is set to the max number of threads available and I remember that has caused test failures when running threaded versions on Mac. My understanding is that the XCode clang compilers don't support OpenMP. If using GCC compilers via homebrew you need the version that does not have `multilib` enabled, otherwise even GCC compilers have issues even if the code is compiled properly with OpenMP flags.

**Comment by spdomin** [comment]
@sayerhs, I am running an "application run" outside of ctest. I will look into the suggestions above - may thanks.

**Comment by spdomin** [comment]
Resolved.
