### ISSUE TITLE
Tests failing due to changes in Trilinos develop branch

### ISSUE THREAD

**Issue by jrood-nrel** [NaluCFD/Nalu#354]
```
	  1 - ablNeutralEdge (Failed)
	 27 - elemHybridFluids (Failed)
	 76 - oversetHybrid (Failed)
	 77 - uqSlidingMeshDG (Failed)
	 78 - waleElemXflowMixFrac3.5m (Failed)
```
due to errors stating:
```
terminate called after throwing an instance of 'Teuchos::Exceptions::InvalidParameterType'
   what():  Error!  An attempt was made to access parameter "mj_premigration_option" of type "int"
 in the parameter (sub)list "ANONYMOUS"
 using the incorrect type "string"!
```

**Comment by kddevin** [comment]
@jhux2 After a closer look, I think the problem is not in how mj_premigration_option is set (string or int); either of those will work.
The problem is that in MueLu_Zoltan2Interface_def.hpp, near line 152, the defaultZoltan2Params list is merged with Zoltan2Params.  In that operation, the parameter value is fetched as a string, instead of as an int.  
        Zoltan2Params.set(pName, defaultZoltan2Params->get<std::string>(pName));
This code probably worked before because all the other Zoltan2 parameters used by MueLu were either strings or did not have validators that checked the type.  Since mj_premigration_option uses EnhancedNumberValidator, its return type for defaultZoltan2Params->get must be int.
Does ParameterList have a method returning the parameter type?  If so, MueLu could check it here and provide the right kind of get() as the second argument.

**Comment by aprokop** [comment]
Being fixed in MueLu.

**Comment by jhux2** [comment]
@jrood-nrel Please let us know if the MueLu patch resolves the Nalu errors.

**Comment by jrood-nrel** [comment]
@jhux2 It looks like this is fixed in the Trilinos develop branch, but it's still lingering in master at the moment.

**Comment by jrood-nrel** [comment]
Looks like this has been fixed in both the develop and master branch of Trilinos.
