### ISSUE TITLE
Diffs on 3 tests

### ISSUE THREAD

**Issue by jrood-nrel** [NaluCFD/Nalu#376]
Tests `elemHybridFluids`, `dgncThreeBladeHypre`, and `nrel5MWactuatorLine` are showing diffs due to commits done on May 2. I am unsure of which specific commit or commits caused the failures.

**Comment by spdomin** [comment]
John. On our side, I am seeing the elemHybridFluids diff. I will look into that ASAP.

**Comment by sayerhs** [comment]
@spdomin Yes, to both symmetry and consolidated algorithms [dgncThreeBladeHypre.i](https://github.com/NaluCFD/Nalu/blob/master/reg_tests/test_files/dgncThreeBladeHypre/dgncThreeBladeHypre.i)

**Comment by spdomin** [comment]
Okay, the dgnc diff is due to the new ordering (back to the original, really) of the exposed faces supplied to all bcs. These should be small and can be re-blessed. With Overfelt's past PR for quad4/tri3 face_grad_op, we can re-activate the symmetry consolidated approach.

The same is true with the nrel5W case - specifically, it uses consolidated and symmetry. This also can be modified to include the true symmetry bc.

**Comment by spdomin** [comment]
John. Ws this resolved?

**Comment by sayerhs** [comment]
@spdomin @jrood-nrel did fix these. See the latest dashboard: https://my.cdash.org/index.php?project=Nalu-Wind

**Comment by jrood-nrel** [comment]
Yes, sorry. The diffs were accepted for the openfast and hypre tests and `elemHybridFluids` was resolved by #378 I believe.
