### ISSUE TITLE
build/test status issue

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#40]
Looks cool (build/test status):

https://github.com/thujohn/twitter

Through Travis_CI?

https://travis-ci.org/thujohn/twitter

**Comment by marchdf** [comment]
I actually spent quite a bit of time looking into something like that (I really wanted it for our readme). It seems that there are other services that you need in order to do that. The biggest seem to be Travis_CI and [CircleCI](https://circleci.com). They didn't seem particularly free but I can look into pricing and if they offer a trial project or time period.

**Comment by spdomin** [comment]
That would be cool. But let's keep everything free or not worry about it. Also it looks like the actual nightly tests are from a forked Nalu code base and not the actual Nalu repos. Do you updat nightly? Let's chat next week.

**Comment by marchdf** [comment]
I just wanted to follow-up with you on a couple things from last week. I was away at a conference and that took up most of my time: 

- Ctest/Cdash ran into some issues because if was using the develop branch of Trilinos and that was giving a configure error. I noticed you switched your Trilinos to master for testing so I did the same for Ctest. What are our thoughts on this? Which one should we be testing again? I can set up so it tests against both if you think that’s a good idea.

- I fixed the Ctest so it points to the actual Nalu repos (and not my fork). The CDash site is now clean (excepting those build warnings). 

- I am working on a set of instructions for adding a test to the CTest suite. 

- TravisCI is free for open source projects. However, it seems more like a service that runs your tests and manages the CI rather than something like CDash which holds the test results. I can't seem to find anyone that actually integrates the two of them into something coherent. My basic understanding is that TravisCI and something like Jenkins are more complete CI tools than CDash. So maybe it's worth taking the next step in CI and going for something like Travis and Jenkins that would eventually supplant the CDash site (while still using CTest of course). Let me know what you think or if you want a call.

**Comment by marchdf** [comment]
File Edit Options Buffers Tools Help
@NaluCFD/core here is a set of instruction for adding tests to the CTest suite. Please let me know if you have any questions. 

# Adding a new test to the CTest suite

There are two files that must be edited when adding a test to the
regression test suite, both located in the `cmake` directory:

- `ctest_prepare_tests.cmake`: sets up the directory structure needed for the test;

- `CTestTestfile.cmake`: defines the test and its properties.

This presumes you have created a directory for your test in the
NaluRtest repo with the appropriate input files, etc.

## `ctest_prepare_tests.cmake`

This file sets up the directory structure needed for the test. It
copies files from the NaluRtest directory into a local testing
directory. You are responsible for ensuring that the proper files are
copied over.

A simple entry in this file would be something like:
```
file(COPY               "${NALURTEST_NIGHTLY_DIR}/periodic3dElem"
     DESTINATION        "${NIGHTLY_TEST_RESULT_DIRECTORY}")

file(COPY               "${NALURTEST_MESH_DIR}/periodic3d.g"
                        "${NALURTEST_XML_DIR}/milestone.xml"
     DESTINATION        "${NIGHTLY_TEST_RESULT_DIRECTORY}/periodic3dElem")
```

This set of commands copies the test directory to a local nightly
directory (including all the files inside of it) and it copies some
extra files located in other directories (such as the mesh and
`milestone.xml`).


A more complicated set of instructions (with file globbing) would look like:
```
file(COPY               "${NALURTEST_NIGHTLY_DIR}/dgNonConformal3dFluidsHexTet"
     DESTINATION        "${NIGHTLY_TEST_RESULT_DIRECTORY}")

file(GLOB meshes        "${NALURTEST_MESH_DIR}/twoBlockMeshHexTet_cgs.g.*")
file(COPY               ${meshes}
                        "${NALURTEST_XML_DIR}/milestone.xml"
     DESTINATION        "${NIGHTLY_TEST_RESULT_DIRECTORY}/dgNonConformal3dFluidsHexTet")
```

## `CTestTestfile.cmake`

This file defines the test and its properties.

A sample entry would look like
```
add_test(periodic3dElemNp4 "periodic3dElemNp4.sh")
set_tests_properties(periodic3dElemNp4
   PROPERTIES  PASS_REGULAR_EXPRESSION "PASSED"
               FAIL_REGULAR_EXPRESSION "FAILED"
   TIMEOUT 400
   PROCESSORS 4
   WORKING_DIRECTORY "${NIGHTLY_TEST_RESULT_DIRECTORY}/periodic3dElem")
```

This defines, in order:

- the test exectutable file (e.g. `periodic3dElemNp4.sh`)

- the regular expression to look for the test status

- the maximum time in seconds run the test before sending an error

- the number of processors to use

- the directory where the test should be run

**Comment by spdomin** [comment]
@marchdf how about adding a new testing platform? I would like to push my Mac results to this page..

**Comment by marchdf** [comment]
@spdomin Working on that now. I need to change a couple small things in the files to enable that.

**Comment by marchdf** [comment]
@spdomin I created a pull request for platform independence. I added some instructions on CTest in the [CTest readme](https://github.com/NaluCFD/Nalu/tree/master/cmake) on how to add a new platform. In theory it should work... I am curious to see how it works in practice. 

I will also be looking at spack to make platform independence easier.

**Comment by spdomin** [comment]
Intel is failing due to the recent HO promotion:

http://my.cdash.org/viewBuildError.php?buildid=1154145

@rcknaus has been notified.

**Comment by spdomin** [comment]
@NaluCFD/core if you pushed 9/7/2017, or had a pull request merged yesterday, please take a look at the dash warnings/failed tests.

**Comment by alanw0** [comment]
I have a fix, simple issue of the selectors used in the unit-tests. Pushing momentarily.

**Comment by spdomin** [comment]
Fail fixed in:

https://github.com/NaluCFD/Nalu/commit/fdf8235aafb0fedbe5862bacbc16117cd966e924
