### ISSUE TITLE
Consolidated approach for momentum when hybrid meshes are in use is wrong

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#84]
I let this one slip... 'should have been more careful in the review.

Basically, the bug is that the consolidated approach logic is only hit when the first interior algorithm type is found.  However, for a hybrid mesh, this does not work. The logic needs to be either consolidated or not. Then, for each part pushed in, the code needs to check the map for the topology if interest. The major complexity is added when element mass is added and in supporting both nodal source terms and the consolidated approach (which I would have preferred to hold off on).

Continuity hybrid looks fine.

**Comment by sayerhs** [comment]
@spdomin I see that the way the if-conditions are set up, the new consolidated alg does not build additional SuppAlg instances for multiple topos. I have a potential fix for this in sayerhs/Nalu@efc5d08ef08ddf . I think this should resolve the issue for both non-consolidated and consolidated Alg setups. Can you share your failing test case with me, so that I can test this and make additional fixes if necessary?

**Comment by spdomin** [comment]
My failing test is the dgNonConformalThreeBlade test that includes bug fixes in ContMass and a newly converted NSO KE flavor. We need to find a test that uses hybrid with one of the suite of SuppAlgs converted. The cylinder in cross flow might be one, however, that probably is using edges.

**Comment by spdomin** [comment]
This is closed...
